name: Node.js CI

permissions:
  contents: write           # Permite leitura e escrita no repositório
  pull-requests: write      # Permite criar e aprovar pull requests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - run: npm ci

    - name: Run tests
      run: npm run test:ci

    - name: Build
      run: npm run build
